### ISSUE TITLE
👷‍♂️ Setup project CI

### ISSUE THREAD

**Issue by Dramloc** [mobility-platform/global-navigation#2]
Project is tested / published manually for now.
We should setup CI / CD to automatically execute tests (any branches) and automatically publish (master only).

GitHub Actions could be used to implement CI / CD.

**Comment by Craaftx** [comment]
Commits for this issue : 75e6f58433e11bfe619bf8ff35c67be0f2ee3a0b, 60506ff3fcaf8765da73039f4125426eeaa9a022, f0abc84ed2a0c9f4e82ff6d9b3780f2a85868877

**Comment by Craaftx** [comment]
We are not yet setting up self-publication on NPM for the moment for organizational reasons with the team, I close the issue for the moment
